import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BookOpen, Printer, RefreshCcw } from 'lucide-react'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Combobox, DataGrid, DateInput, EmptyState, FormField, FormSection, Input, MoneyInput, PageHeader, Select, StatCard, StatusPill, exportRowsToExcel } from '@/components/ui'
import { useHotkeys } from '@/hooks/useHotkeys'
import { formatDate, formatMoney } from '@/lib/format'
import { ledgerApi, type FsAccount, type FsBank, type FsJournalLine, type FsSignatory, type FsSupplier, type FsVoucherLine, type FsVoucherMaster } from '@/api/ledger'

const today = () => new Date().toISOString().slice(0, 10)
const unwrap = <T,>(v?: { data: T[] }) => v?.data ?? []
const money = (v?: number | null) => <span className="font-mono tabular-nums">{formatMoney(v ?? 0)}</span>
const errorText = (e: unknown) => e instanceof Error ? e.message : 'Request failed. Review required fields and role/period guards.'
const accountsForCombo = (rows: FsAccount[]) => rows.filter((a) => a.isActive !== false && ['DC', 'CD'].includes(String(a.formula))).map((a) => ({ id: a.acctCode, label: `${a.acctCode} — ${a.acctDesc}`, description: a.glReport }))
function Msg({ text }: { text: string }) { return text ? <p className="mb-3 rounded-md border bg-card p-2 text-sm text-muted-foreground">{text}</p> : null }
function printHtml(title: string, html: string) { const w = window.open('', '_blank'); if (!w) return; w.document.write(`<!doctype html><title>${title}</title><style>body{font-family:Arial;margin:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:6px}.num{text-align:right;font-family:monospace}@media print{button{display:none}}</style><button onclick="print()">Print</button>${html}`); w.document.close() }

export function LedgerOverviewPage() {
  const info = useQuery({ queryKey: ['fs-system-info'], queryFn: () => ledgerApi.systemInfo() })
  const rows = Object.entries(info.data ?? {}).filter(([k]) => k.startsWith('unposted')).map(([k, v]) => ({ id: k, label: k.replace('unposted', '').replace(/([A-Z])/g, ' $1').trim(), count: Number(v || 0) }))
  return <div><PageHeader eyebrow="FS Ledger" title="Fiscal ledger overview" description="Current period, unposted book counts and shortcuts for journals, posting, reports and month-end." /><div className="grid gap-4 md:grid-cols-4"><StatCard label="Current month" value={`${info.data?.currentMonth ?? '—'}/${info.data?.currentYear ?? '—'}`} icon={<BookOpen className="size-5" />} /><StatCard label="Period begin" value={formatDate(info.data?.begDate as string)} /><StatCard label="Period end" value={formatDate(info.data?.endDate as string)} /><StatCard label="Total unposted" value={String(info.data?.totalUnposted ?? 0)} /></div><Card className="mt-4"><CardHeader><CardTitle>Unposted workload</CardTitle></CardHeader><CardContent><DataGrid data={rows} columns={[{ id: 'book', header: 'Book', accessor: 'label' }, { id: 'count', header: 'Count', accessor: 'count', className: 'text-right' }]} /></CardContent></Card></div>
}

export function ChartOfAccountsPage() {
  const qc = useQueryClient(); const [msg, setMsg] = useState(''); const [form, setForm] = useState<Partial<FsAccount>>({ formula: 'DC', isActive: true })
  const q = useQuery({ queryKey: ['fs-accounts'], queryFn: () => ledgerApi.accounts() })
  const save = useMutation({ mutationFn: () => form.acctCode ? ledgerApi.updateAccount(form.acctCode, form) : ledgerApi.createAccount(form), onSuccess: () => qc.invalidateQueries({ queryKey: ['fs-accounts'] }), onError: (e) => setMsg(errorText(e)) })
  const rows = unwrap(q.data); const groups = useMemo(() => rows.reduce<Record<string, FsAccount[]>>((m, a) => { const key = a.glReport || a.groupCode || 'UNGROUPED'; (m[key] ||= []).push(a); return m }, {}), [rows])
  return <div><PageHeader eyebrow="Ledger" title="Chart of accounts" description="Tree grouped by report group with normal balance, postable/header status and balances. CRUD is server role-gated." primaryAction={<Button onClick={() => save.mutate()} loading={save.isPending}>Save account</Button>} /><Msg text={msg} /><div className="grid gap-4 xl:grid-cols-[24rem_1fr]"><Card><CardHeader><CardTitle>Account maintenance</CardTitle></CardHeader><CardContent className="grid gap-3"><FormField label="Code"><Input value={form.acctCode ?? ''} onChange={(e) => setForm({ ...form, acctCode: e.target.value.toUpperCase() })} /></FormField><FormField label="Description"><Input value={form.acctDesc ?? ''} onChange={(e) => setForm({ ...form, acctDesc: e.target.value })} /></FormField><FormField label="Report group"><Input value={form.glReport ?? ''} onChange={(e) => setForm({ ...form, glReport: e.target.value.toUpperCase() })} /></FormField><FormField label="Normal balance / postable"><Select value={String(form.formula ?? 'DC')} onValueChange={(v) => setForm({ ...form, formula: v })} options={[{ value: 'DC', label: 'Debit normal / postable' }, { value: 'CD', label: 'Credit normal / postable' }, { value: 'H', label: 'Header' }]} /></FormField><FormField label="Opening balance"><MoneyInput value={form.openBal ?? 0} onValueChange={(v) => setForm({ ...form, openBal: v })} /></FormField></CardContent></Card><div className="space-y-3">{Object.entries(groups).map(([g, list]) => <Card key={g}><CardHeader><CardTitle>{g}</CardTitle><CardDescription>{list.length} accounts</CardDescription></CardHeader><CardContent><DataGrid data={list} density="compact" onRowSelect={(r) => setForm(r[0] ?? form)} columns={[{ id: 'code', header: 'Code', accessor: 'acctCode' }, { id: 'desc', header: 'Description', accessor: 'acctDesc' }, { id: 'normal', header: 'Normal', accessor: 'formula' }, { id: 'postable', header: 'Type', cell: (r) => ['DC','CD'].includes(String(r.formula)) ? <StatusPill status="postable" tone="success" /> : <StatusPill status="header" /> }, { id: 'debit', header: 'Debit', cell: (r) => money(r.curDebit ?? r.debitMovement), className: 'text-right' }, { id: 'credit', header: 'Credit', cell: (r) => money(r.curCredit ?? r.creditMovement), className: 'text-right' }, { id: 'end', header: 'Ending', cell: (r) => money(r.endBal ?? r.endingBalance), className: 'text-right' }]} /></CardContent></Card>)}</div></div></div>
}

export function JournalPage({ kind = 'general' }: { kind?: string }) {
  const qc = useQueryClient(); const [msg, setMsg] = useState(''); const [ref, setRef] = useState(`JV-${Date.now()}`); const [date, setDate] = useState(today()); const [lines, setLines] = useState<Array<Partial<FsJournalLine>>>([{ jJvNo: ref, jDate: date, jDOrC: 'D', jCkAmt: 0 }, { jJvNo: ref, jDate: date, jDOrC: 'C', jCkAmt: 0 }])
  const accts = useQuery({ queryKey: ['fs-accounts'], queryFn: () => ledgerApi.accounts() }); const q = useQuery({ queryKey: ['fs-journal', kind], queryFn: () => ledgerApi.journal(kind) })
  const debit = lines.filter((l) => l.jDOrC === 'D').reduce((s, l) => s + Number(l.jCkAmt || 0), 0); const credit = lines.filter((l) => l.jDOrC === 'C').reduce((s, l) => s + Number(l.jCkAmt || 0), 0)
  const save = useMutation({ mutationFn: async () => { for (const l of lines.filter((x) => x.acctCode && Number(x.jCkAmt))) await ledgerApi.createJournalLine(kind, { ...l, jJvNo: ref, jDate: date }); }, onSuccess: () => qc.invalidateQueries({ queryKey: ['fs-journal', kind] }), onError: (e) => setMsg(errorText(e)) })
  const act = useMutation({ mutationFn: (op: string) => op === 'trial' ? ledgerApi.trialJournal(kind, ref) : ledgerApi.postJournal(kind, ref), onSuccess: (r) => setMsg(JSON.stringify(r)), onError: (e) => setMsg(errorText(e)) })
  useHotkeys([{ key: 'Mod+S', description: 'Save', handler: () => save.mutate() }, { key: 'Mod+Enter', description: 'Post', handler: () => act.mutate('post') }, { key: 'Alt+ArrowDown', description: 'Add line', handler: () => setLines([...lines, { jJvNo: ref, jDate: date, jDOrC: 'D', jCkAmt: 0 }]) }])
  return <div><PageHeader eyebrow="Journals" title={`${kind.toUpperCase()} entry`} description="Header and line entry with account combobox, live Dr/Cr balance, trial and final post." primaryAction={<Button onClick={() => save.mutate()} loading={save.isPending} kbd="Ctrl+S">Save lines</Button>} actions={<><Button variant="outline" onClick={() => act.mutate('trial')}>Trial</Button><Button onClick={() => act.mutate('post')} disabled={Math.abs(debit - credit) > 0.01} kbd="Ctrl+Enter">Post</Button></>} /><Msg text={msg} /><Card><CardHeader><CardTitle>Entry header</CardTitle><CardDescription className={Math.abs(debit - credit) > 0.01 ? 'text-destructive' : 'text-success'}>Debit {formatMoney(debit)} / Credit {formatMoney(credit)} / Difference {formatMoney(debit - credit)}</CardDescription></CardHeader><CardContent className="grid gap-4"><FormSection title="Header"><FormField label="Reference"><Input value={ref} onChange={(e) => { setRef(e.target.value); setLines(lines.map((l) => ({ ...l, jJvNo: e.target.value }))) }} /></FormField><FormField label="Date"><DateInput value={date} onValueChange={(v) => { setDate(v); setLines(lines.map((l) => ({ ...l, jDate: v }))) }} /></FormField></FormSection><JournalLines accounts={unwrap(accts.data)} lines={lines} setLines={setLines} /></CardContent></Card><Card className="mt-4"><CardHeader><CardTitle>Existing unposted lines</CardTitle></CardHeader><CardContent><DataGrid data={unwrap(q.data)} density="compact" columns={[{ id: 'ref', header: 'Ref', accessor: 'jJvNo' }, { id: 'date', header: 'Date', cell: (r) => formatDate(r.jDate) }, { id: 'acct', header: 'Account', accessor: 'acctCode' }, { id: 'dc', header: 'D/C', accessor: 'jDOrC' }, { id: 'amt', header: 'Amount', cell: (r) => money(r.jCkAmt), className: 'text-right' }]} /></CardContent></Card></div>
}
function JournalLines({ accounts, lines, setLines }: { accounts: FsAccount[]; lines: Array<Partial<FsJournalLine>>; setLines: (v: Array<Partial<FsJournalLine>>) => void }) { const patch = (i: number, p: Partial<FsJournalLine>) => setLines(lines.map((l, n) => n === i ? { ...l, ...p } : l)); return <div className="overflow-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-muted"><tr><th>Account</th><th>D/C</th><th className="text-right">Amount</th></tr></thead><tbody>{lines.map((l, i) => <tr key={i} className="border-t"><td><Combobox items={accountsForCombo(accounts)} value={l.acctCode} onSelect={(a) => patch(i, { acctCode: a.id })} /></td><td><Select value={l.jDOrC ?? 'D'} onValueChange={(v) => patch(i, { jDOrC: v as 'D' | 'C' })} options={[{ value: 'D', label: 'Debit' }, { value: 'C', label: 'Credit' }]} /></td><td><MoneyInput value={l.jCkAmt ?? 0} onValueChange={(v) => patch(i, { jCkAmt: v })} /></td></tr>)}</tbody></table><Button className="m-2" variant="outline" size="sm" onClick={() => setLines([...lines, { jDOrC: 'D', jCkAmt: 0 }])}>Add line Alt+↓</Button></div> }

export function VoucherPage() {
  const qc = useQueryClient(); const [msg, setMsg] = useState(''); const [type, setType] = useState('current'); const [master, setMaster] = useState<Partial<FsVoucherMaster>>({ jDate: today(), jCkAmt: 0 }); const [lines, setLines] = useState<Array<Partial<FsVoucherLine>>>([])
  const masters = useQuery({ queryKey: ['fs-vouchers', type], queryFn: () => ledgerApi.voucherMasters(type) }); const accts = useQuery({ queryKey: ['fs-accounts'], queryFn: () => ledgerApi.accounts() }); const banks = useQuery({ queryKey: ['fs-banks'], queryFn: () => ledgerApi.banks() }); const sups = useQuery({ queryKey: ['fs-suppliers'], queryFn: () => ledgerApi.suppliers() })
  const dr = lines.filter((l) => l.jDOrC === 'D').reduce((s, l) => s + Number(l.jCkAmt || 0), 0); const cr = lines.filter((l) => l.jDOrC === 'C').reduce((s, l) => s + Number(l.jCkAmt || 0), 0)
  const save = useMutation({ mutationFn: async () => { const m = await ledgerApi.createVoucherMaster(master); for (const l of lines.filter((x) => x.acctCode && Number(x.jCkAmt))) await ledgerApi.createVoucherLine({ ...l, jCkNo: m.data.jCkNo }); return m }, onSuccess: () => qc.invalidateQueries({ queryKey: ['fs-vouchers', type] }), onError: (e) => setMsg(errorText(e)) })
  return <div><PageHeader eyebrow="Vouchers" title="Cash disbursement vouchers" description="CDB check voucher master and detail lines using new /fs/vouchers endpoints." actions={<Select value={type} onValueChange={setType} options={[{ value: 'current', label: 'Current' }, { value: 'advance', label: 'Advance' }, { value: 'all', label: 'All' }]} />} primaryAction={<Button onClick={() => save.mutate()} loading={save.isPending}>Save voucher</Button>} /><Msg text={msg} /><div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Voucher entry</CardTitle><CardDescription className={Math.abs(dr - cr) > 0.01 ? 'text-destructive' : 'text-success'}>Dr {formatMoney(dr)} / Cr {formatMoney(cr)}</CardDescription></CardHeader><CardContent className="grid gap-4"><FormSection title="Master"><FormField label="JV / voucher no"><Input value={master.jJvNo ?? ''} onChange={(e) => setMaster({ ...master, jJvNo: e.target.value, jCkNo: master.jCkNo || e.target.value })} /></FormField><FormField label="Check no"><Input value={master.jCkNo ?? ''} onChange={(e) => setMaster({ ...master, jCkNo: e.target.value })} /></FormField><FormField label="Date"><DateInput value={master.jDate} onValueChange={(v) => setMaster({ ...master, jDate: v })} /></FormField><FormField label="Pay to"><Input value={master.jPayTo ?? ''} onChange={(e) => setMaster({ ...master, jPayTo: e.target.value })} /></FormField><FormField label="Bank"><Select value={String(master.bankNo ?? '')} onValueChange={(v) => setMaster({ ...master, bankNo: Number(v) })} options={unwrap(banks.data).map((b: FsBank) => ({ value: String(b.bankNo), label: b.bankName }))} /></FormField><FormField label="Supplier"><Select value={String(master.supNo ?? '')} onValueChange={(v) => setMaster({ ...master, supNo: Number(v) })} options={unwrap(sups.data).map((s: FsSupplier) => ({ value: String(s.supNo), label: s.supName }))} /></FormField><FormField label="Amount"><MoneyInput value={master.jCkAmt ?? 0} onValueChange={(v) => setMaster({ ...master, jCkAmt: v })} /></FormField></FormSection><VoucherLines accounts={unwrap(accts.data)} lines={lines} setLines={setLines} /></CardContent></Card><DataGrid data={unwrap(masters.data)} loading={masters.isLoading} columns={[{ id: 'jv', header: 'JV', accessor: 'jJvNo' }, { id: 'check', header: 'Check', accessor: 'jCkNo' }, { id: 'date', header: 'Date', cell: (r) => formatDate(r.jDate) }, { id: 'pay', header: 'Pay to', accessor: 'jPayTo' }, { id: 'amt', header: 'Amount', cell: (r) => money(r.jCkAmt), className: 'text-right' }]} /></div></div>
}
function VoucherLines({ accounts, lines, setLines }: { accounts: FsAccount[]; lines: Array<Partial<FsVoucherLine>>; setLines: (v: Array<Partial<FsVoucherLine>>) => void }) { const patch = (i: number, p: Partial<FsVoucherLine>) => setLines(lines.map((l, n) => n === i ? { ...l, ...p } : l)); return <div className="overflow-auto rounded-xl border"><table className="w-full text-sm"><tbody>{lines.map((l, i) => <tr key={i} className="border-t"><td><Combobox items={accountsForCombo(accounts)} value={l.acctCode} onSelect={(a) => patch(i, { acctCode: a.id })} /></td><td><Select value={l.jDOrC ?? 'D'} onValueChange={(v) => patch(i, { jDOrC: v as 'D' | 'C' })} options={[{ value: 'D', label: 'Debit' }, { value: 'C', label: 'Credit' }]} /></td><td><MoneyInput value={l.jCkAmt ?? 0} onValueChange={(v) => patch(i, { jCkAmt: v })} /></td></tr>)}</tbody></table><Button className="m-2" variant="outline" size="sm" onClick={() => setLines([...lines, { jDOrC: 'D', jCkAmt: 0 }])}>Add line</Button></div> }

export function ReportsPage() {
  const [type, setType] = useState('trial-balance'); const [from, setFrom] = useState(today().slice(0, 8) + '01'); const [to, setTo] = useState(today())
  const q = useQuery({ queryKey: ['fs-report', type, from, to], queryFn: () => ledgerApi.report(type, { from, to }) })
  const rows = (q.data?.lines ?? []) as Array<Record<string, unknown>>
  const gridRows: Array<Record<string, unknown> & { id: number }> = rows.map((r, i) => ({ id: i, ...r }))
  const asString = (r: Record<string, unknown>, keys: string[]) => String(keys.map((k) => r[k]).find((v) => v !== undefined && v !== null) ?? '')
  const asNumber = (v: unknown) => Number(v ?? 0)
  return <div><PageHeader eyebrow="Reports" title="FS reports" description="Trial balance, balance sheet, income statement, GL detail and books from /fs/reports/:type." actions={<><Select value={type} onValueChange={setType} options={['trial-balance','balance-sheet','income-statement','general-ledger','cdv','receipts','sales','journals','purchase','adjustments'].map((v) => ({ value: v, label: v }))} /><DateInput value={from} onValueChange={setFrom} /><DateInput value={to} onValueChange={setTo} /></>} primaryAction={<Button variant="outline" onClick={() => exportRowsToExcel(rows, `${type}.xlsx`)}>Excel</Button>} /><div className="grid gap-4 md:grid-cols-3"><StatCard label="Total debit" value={money(q.data?.totalDebit)} /><StatCard label="Total credit" value={money(q.data?.totalCredit)} /><StatCard label="Balance" value={<StatusPill status={q.data?.inBalance ? 'balanced' : 'review'} tone={q.data?.inBalance ? 'success' : 'warning'} />} /></div><Card className="mt-4"><CardHeader className="flex-row justify-between"><CardTitle>{type}</CardTitle><Button variant="outline" size="sm" onClick={() => printHtml(type, `<h1>${type}</h1><pre>${JSON.stringify(rows, null, 2)}</pre>`)}><Printer className="size-4" />Print</Button></CardHeader><CardContent><DataGrid data={gridRows} loading={q.isLoading} columns={[{ id: 'ref', header: 'Ref/Acct', cell: (r) => asString(r, ['acctCode', 'refNo', 'jJvNo', 'jCkNo']) }, { id: 'desc', header: 'Description', cell: (r) => asString(r, ['acctDesc', 'jPayTo', 'memo']) }, { id: 'date', header: 'Date', cell: (r) => formatDate(asString(r, ['jDate', 'date'])) }, { id: 'debit', header: 'Debit', cell: (r) => money(r.debitMovement !== undefined ? asNumber(r.debitMovement) : r.jDOrC === 'D' ? asNumber(r.jCkAmt) : 0), className: 'text-right' }, { id: 'credit', header: 'Credit', cell: (r) => money(r.creditMovement !== undefined ? asNumber(r.creditMovement) : r.jDOrC === 'C' ? asNumber(r.jCkAmt) : 0), className: 'text-right' }, { id: 'ending', header: 'Ending', cell: (r) => money(asNumber(r.endingBalance ?? r.endBal ?? r.runningBalance)), className: 'text-right' }]} /></CardContent></Card></div>
}

export function PostingPage() {
  const [msg, setMsg] = useState(''); const post = useMutation({ mutationFn: () => ledgerApi.posting(), onSuccess: (r) => setMsg(JSON.stringify(r)), onError: (e) => setMsg(errorText(e)) }); const info = useQuery({ queryKey: ['fs-system-info'], queryFn: () => ledgerApi.systemInfo() })
  return <div><PageHeader eyebrow="Posting" title="Bulk posting" description="Runs /fs/posting against staged book rows, validates balance, writes fs_pournals and recomputes balances." primaryAction={<Button onClick={() => post.mutate()} loading={post.isPending}><RefreshCcw className="size-4" />Run posting</Button>} /><Msg text={msg} /><div className="grid gap-4 md:grid-cols-3"><StatCard label="Unposted total" value={String(info.data?.totalUnposted ?? 0)} /><StatCard label="Company" value={String(info.data?.companyCode ?? '—')} /><StatCard label="Period" value={`${formatDate(info.data?.begDate as string)}–${formatDate(info.data?.endDate as string)}`} /></div></div>
}

export function MonthEndPage() {
  const [msg, setMsg] = useState(''); const q = useQuery({ queryKey: ['fs-month-end'], queryFn: () => ledgerApi.monthEndChecklist() }); const close = useMutation({ mutationFn: () => ledgerApi.closeMonth(), onSuccess: (r) => setMsg(JSON.stringify(r)), onError: (e) => setMsg(errorText(e)) }); const d = q.data?.data
  return <div><PageHeader eyebrow="Month-end" title="Month-end close" description="Checklist and close action using the new /fs/month-end/checklist and /fs/month-end/close endpoints." primaryAction={<Button disabled={!d?.ok} onClick={() => confirm('Close current FS period?') && close.mutate()} loading={close.isPending}>Close month</Button>} /><Msg text={msg} />{d ? <div className="grid gap-4 md:grid-cols-3"><StatCard label="Trial balance" value={<StatusPill status={d.tbBalanced ? 'balanced' : 'out of balance'} tone={d.tbBalanced ? 'success' : 'danger'} />} /><StatCard label="Unposted" value={String(d.unposted)} /><StatCard label="Ready" value={<StatusPill status={d.ok ? 'ready' : 'blocked'} tone={d.ok ? 'success' : 'warning'} />} /></div> : <EmptyState title="No checklist loaded" />}<Card className="mt-4"><CardHeader><CardTitle>Checklist detail</CardTitle></CardHeader><CardContent>{d && Object.entries(d.counts).map(([k, v]) => <p key={k} className="flex justify-between border-b py-2"><span>{k}</span><span className="font-mono">{v}</span></p>)}</CardContent></Card></div>
}

export function DirectoryPage({ kind }: { kind: 'banks' | 'suppliers' | 'signatories' }) {
  const qc = useQueryClient(); const [msg, setMsg] = useState(''); const [form, setForm] = useState<Partial<FsSignatory>>({ isActive: true })
  const q = useQuery<{ data: unknown[] }>({ queryKey: ['fs-dir', kind], queryFn: async () => kind === 'banks' ? ledgerApi.banks() : kind === 'suppliers' ? ledgerApi.suppliers() : ledgerApi.signatories() })
  const save = useMutation({ mutationFn: () => ledgerApi.createSignatory(form), onSuccess: () => qc.invalidateQueries({ queryKey: ['fs-dir', kind] }), onError: (e) => setMsg(errorText(e)) })
  const rows = unwrap(q.data).map((r, i) => ({ id: (r as { id?: string | number }).id ?? i, ...(r as Record<string, unknown>) })) as Array<Record<string, unknown> & { id: string | number }>
  const keys = Object.keys(rows[0] ?? { id: '', name: '' }).slice(0, 6)
  return <div><PageHeader eyebrow="FS setup" title={kind[0].toUpperCase() + kind.slice(1)} description={kind === 'signatories' ? 'Active signatories used on vouchers.' : 'Read-only FS reference list from accounting.db.'} primaryAction={kind === 'signatories' ? <Button onClick={() => save.mutate()}>Save signatory</Button> : undefined} /><Msg text={msg} />{kind === 'signatories' && <Card className="mb-4"><CardHeader><CardTitle>Signatory maintenance</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><FormField label="Name"><Input value={form.signName ?? ''} onChange={(e) => setForm({ ...form, signName: e.target.value })} /></FormField><FormField label="Title"><Input value={form.signTitle ?? ''} onChange={(e) => setForm({ ...form, signTitle: e.target.value })} /></FormField><FormField label="Active"><Select value={String(form.isActive ?? true)} onValueChange={(v) => setForm({ ...form, isActive: v === 'true' })} options={[{ value: 'true', label: 'Active' }, { value: 'false', label: 'Inactive' }]} /></FormField></CardContent></Card>}<DataGrid data={rows} loading={q.isLoading} columns={keys.map((k) => ({ id: k, header: k, cell: (r: Record<string, unknown>) => String(r[k] ?? '') }))} /></div>
}
