import { useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, FileDown, Search, Truck, UserRound } from 'lucide-react'
import { toast } from 'sonner'
import { Button, Card, CardHeader, CardTitle, DataGrid, type DataGridColumn, exportRowsToExcel, FormField, FormSection, Input, PageHeader, Select, Sheet, SheetContent, StatusPill, Textarea, Toolbar } from '@/components/ui'
import { useHotkeys } from '@/hooks/useHotkeys'
import { formatDate } from '@/lib/format'
import { fleetApi, type DispatchRoute, type DispatchRouteInput, type Driver, type DriverInput, type FleetVehicle, type FleetVehicleInput } from '@/api/fleet'

function err(e: unknown) { return e instanceof Error ? e.message : 'Request failed' }
function todayIso() { return new Date().toISOString().slice(0, 10) }
function expiring(text?: string | null) { if (!text) return false; const d = new Date(text); if (Number.isNaN(d.getTime())) return false; const days = (d.getTime() - Date.now()) / 86400000; return days >= 0 && days <= 30 }

export default function FleetDispatchPage() {
  const qc = useQueryClient()
  const [tab, setTab] = useState('routes')
  const [q, setQ] = useState('')
  const [sheet, setSheet] = useState<null | { kind: 'driver' | 'vehicle' | 'route'; id?: string }>(null)
  const [driver, setDriver] = useState<DriverInput>({ name: '', status: 'AVAILABLE' })
  const [vehicle, setVehicle] = useState<FleetVehicleInput>({ plateNo: '', status: 'AVAILABLE' })
  const [route, setRoute] = useState<DispatchRouteInput>({ stage: 'DRAFT', scheduledAt: new Date().toISOString().slice(0, 16) })
  const searchRef = useRef<HTMLInputElement>(null)
  const drivers = useQuery({ queryKey: ['fleet-drivers', q], queryFn: () => fleetApi.drivers({ q, pageSize: 200 }) })
  const vehicles = useQuery({ queryKey: ['fleet-vehicles', q], queryFn: () => fleetApi.vehicles({ q, pageSize: 200 }) })
  const routes = useQuery({ queryKey: ['dispatch-routes', q], queryFn: () => fleetApi.routes({ q, pageSize: 200 }) })
  const saveDriver = useMutation({ mutationFn: () => sheet?.id ? fleetApi.updateDriver(sheet.id, driver) : fleetApi.createDriver(driver), onSuccess: () => { toast.success('Driver saved'); setSheet(null); qc.invalidateQueries({ queryKey: ['fleet-drivers'] }) }, onError: (e) => toast.error(err(e)) })
  const saveVehicle = useMutation({ mutationFn: () => sheet?.id ? fleetApi.updateVehicle(sheet.id, vehicle) : fleetApi.createVehicle(vehicle), onSuccess: () => { toast.success('Fleet vehicle saved'); setSheet(null); qc.invalidateQueries({ queryKey: ['fleet-vehicles'] }) }, onError: (e) => toast.error(err(e)) })
  const saveRoute = useMutation({ mutationFn: () => sheet?.id ? fleetApi.updateRoute(sheet.id, route) : fleetApi.createRoute(route), onSuccess: () => { toast.success('Dispatch route saved'); setSheet(null); qc.invalidateQueries({ queryKey: ['dispatch-routes'] }) }, onError: (e) => toast.error(err(e)) })
  const openNew = () => { if (tab === 'drivers') { setDriver({ name: '', status: 'AVAILABLE' }); setSheet({ kind: 'driver' }) } else if (tab === 'vehicles') { setVehicle({ plateNo: '', status: 'AVAILABLE' }); setSheet({ kind: 'vehicle' }) } else { setRoute({ stage: 'DRAFT', scheduledAt: new Date().toISOString().slice(0, 16) }); setSheet({ kind: 'route' }) } }
  useHotkeys([{ key: 'N', description: 'New fleet row', handler: openNew }, { key: '/', description: 'Search fleet', handler: () => searchRef.current?.focus() }, { key: 'Escape', description: 'Close panel', handler: () => setSheet(null), when: !!sheet }, { key: 'Mod+S', description: 'Save', handler: () => sheet?.kind === 'driver' ? saveDriver.mutate() : sheet?.kind === 'vehicle' ? saveVehicle.mutate() : sheet?.kind === 'route' ? saveRoute.mutate() : undefined, when: !!sheet }])
  const routeRows = routes.data?.data ?? []
  const driverRows = drivers.data?.data ?? []
  const vehicleRows = vehicles.data?.data ?? []
  return <div className="space-y-5 p-4 md:p-6"><PageHeader title="Fleet & Dispatch" eyebrow="Operations" description="Fleet vehicle master, driver master, and dispatch route manifests. Schema has plate/type/capacity/status and driver license/phone/status; registration/insurance expiry fields are not exposed by the backend." primaryAction={<Button onClick={openNew} kbd="N">New {tab.slice(0, -1) || 'route'}</Button>} actions={<Button variant="outline" onClick={() => exportRowsToExcel((tab === 'drivers' ? driverRows : tab === 'vehicles' ? vehicleRows : routeRows) as unknown as Record<string, unknown>[], `fleet-${tab}-${todayIso()}.xlsx`)}><FileDown className="size-4" />Export manifest</Button>} />
    <Toolbar><Input ref={searchRef} leftIcon={<Search className="size-4" />} value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search fleet, driver, route…" className="w-80" /><Select value={tab} onValueChange={setTab} options={[{ value: 'routes', label: 'Dispatch routes' }, { value: 'vehicles', label: 'Truck / vehicle master' }, { value: 'drivers', label: 'Drivers master' }]} /></Toolbar>
    <div className="grid gap-3 md:grid-cols-4"><Card><CardHeader className="py-3"><CardTitle className="flex justify-between text-sm"><span>Routes today</span><span className="font-mono">{routeRows.filter((r) => r.scheduledAt?.startsWith(todayIso())).length}</span></CardTitle></CardHeader></Card><Card><CardHeader className="py-3"><CardTitle className="flex justify-between text-sm"><span>Available drivers</span><span className="font-mono">{driverRows.filter((d) => d.status === 'AVAILABLE').length}</span></CardTitle></CardHeader></Card><Card><CardHeader className="py-3"><CardTitle className="flex justify-between text-sm"><span>Available trucks</span><span className="font-mono">{vehicleRows.filter((v) => v.status === 'AVAILABLE').length}</span></CardTitle></CardHeader></Card><Card><CardHeader className="py-3"><CardTitle className="flex justify-between text-sm"><span>Expiry warnings</span><span className="font-mono">{driverRows.filter((d) => expiring(d.licenseNo)).length}</span></CardTitle></CardHeader></Card></div>
    {tab === 'routes' && <RoutesTable rows={routeRows} loading={routes.isLoading} onEdit={(r) => { setRoute(r); setSheet({ kind: 'route', id: r.id }) }} />}
    {tab === 'vehicles' && <VehicleTable rows={vehicleRows} loading={vehicles.isLoading} onEdit={(v) => { setVehicle(v); setSheet({ kind: 'vehicle', id: v.id }) }} />}
    {tab === 'drivers' && <DriverTable rows={driverRows} loading={drivers.isLoading} onEdit={(d) => { setDriver(d); setSheet({ kind: 'driver', id: d.id }) }} />}
    <Sheet open={!!sheet} onOpenChange={(v) => !v && setSheet(null)}><SheetContent title={sheet?.kind === 'driver' ? 'Driver master' : sheet?.kind === 'vehicle' ? 'Fleet vehicle master' : 'Dispatch route'} description="Ctrl+S saves; Esc closes." className="w-[min(42rem,100vw)] overflow-y-auto">{sheet?.kind === 'driver' && <DriverEditor draft={driver} setDraft={setDriver} save={() => saveDriver.mutate()} saving={saveDriver.isPending} />}{sheet?.kind === 'vehicle' && <FleetVehicleEditor draft={vehicle} setDraft={setVehicle} save={() => saveVehicle.mutate()} saving={saveVehicle.isPending} />}{sheet?.kind === 'route' && <RouteEditor draft={route} setDraft={setRoute} save={() => saveRoute.mutate()} saving={saveRoute.isPending} drivers={driverRows} vehicles={vehicleRows} />}</SheetContent></Sheet>
  </div>
}
function RoutesTable({ rows, loading, onEdit }: { rows: DispatchRoute[]; loading: boolean; onEdit: (r: DispatchRoute) => void }) { const cols: DataGridColumn<DispatchRoute>[] = [{ id: 'routeNo', header: 'Route #', cell: (r) => <button className="font-mono text-secondary underline-offset-4 hover:underline" onClick={() => onEdit(r)}>{r.routeNo}</button>, sortable: true }, { id: 'stage', header: 'Stage', cell: (r) => <StatusPill status={r.stage} /> }, { id: 'origin', header: 'Origin', accessor: 'origin' }, { id: 'destination', header: 'Destination', accessor: 'destination' }, { id: 'driver', header: 'Driver', accessor: 'driverName' }, { id: 'vehicle', header: 'Vehicle', accessor: 'vehiclePlate' }, { id: 'scheduled', header: 'Scheduled', cell: (r) => formatDate(r.scheduledAt) }, { id: 'pod', header: 'POD', cell: (r) => r.podSignedBy ? `Signed by ${r.podSignedBy}` : '—' }]; return <DataGrid columns={cols} data={rows} loading={loading} emptyTitle="No dispatch routes" density="compact" /> }
function VehicleTable({ rows, loading, onEdit }: { rows: FleetVehicle[]; loading: boolean; onEdit: (r: FleetVehicle) => void }) { const cols: DataGridColumn<FleetVehicle>[] = [{ id: 'plateNo', header: 'Plate', cell: (r) => <button className="font-mono text-secondary underline-offset-4 hover:underline" onClick={() => onEdit(r)}>{r.plateNo}</button>, sortable: true }, { id: 'type', header: 'Type', accessor: 'type' }, { id: 'make', header: 'Make/model', accessor: 'make' }, { id: 'capacity', header: 'Capacity', accessor: 'capacity' }, { id: 'status', header: 'Status', cell: (r) => <StatusPill status={r.status} /> }]; return <DataGrid columns={cols} data={rows} loading={loading} emptyTitle="No fleet vehicles" density="compact" /> }
function DriverTable({ rows, loading, onEdit }: { rows: Driver[]; loading: boolean; onEdit: (r: Driver) => void }) { const cols: DataGridColumn<Driver>[] = [{ id: 'name', header: 'Driver', cell: (r) => <button className="font-semibold text-secondary underline-offset-4 hover:underline" onClick={() => onEdit(r)}>{r.name}</button>, sortable: true }, { id: 'license', header: 'License', cell: (r) => <span className="inline-flex items-center gap-1">{r.licenseNo || '—'}{expiring(r.licenseNo) && <AlertTriangle className="size-3 text-warning" />}</span> }, { id: 'phone', header: 'Phone', accessor: 'phone' }, { id: 'plateHint', header: 'Usual plate', accessor: 'plateHint' }, { id: 'status', header: 'Status', cell: (r) => <StatusPill status={r.status} /> }]; return <DataGrid columns={cols} data={rows} loading={loading} emptyTitle="No drivers" density="compact" /> }
function DriverEditor({ draft, setDraft, save, saving }: { draft: DriverInput; setDraft: (v: DriverInput) => void; save: () => void; saving: boolean }) { const set = (p: DriverInput) => setDraft({ ...draft, ...p }); return <div className="space-y-4"><FormSection title="Driver"><FormField label="Name" required><Input value={draft.name ?? ''} onChange={(e) => set({ name: e.target.value })} leftIcon={<UserRound className="size-4" />} /></FormField><FormField label="License no / expiry"><><Input value={draft.licenseNo ?? ''} onChange={(e) => set({ licenseNo: e.target.value })} /><p className="text-xs text-muted-foreground">Backend has one licenseNo field; use ISO date here to activate expiry warnings.</p></></FormField><FormField label="Phone"><Input value={draft.phone ?? ''} onChange={(e) => set({ phone: e.target.value })} /></FormField><FormField label="Plate hint"><Input value={draft.plateHint ?? ''} onChange={(e) => set({ plateHint: e.target.value })} /></FormField><FormField label="Status"><Select value={draft.status ?? 'AVAILABLE'} onValueChange={(status) => set({ status })} options={['AVAILABLE', 'ASSIGNED', 'OFF_DUTY', 'SUSPENDED'].map((value) => ({ value, label: value }))} /></FormField></FormSection><div className="flex justify-end"><Button onClick={save} loading={saving} kbd="Ctrl+S">Save</Button></div></div> }
function FleetVehicleEditor({ draft, setDraft, save, saving }: { draft: FleetVehicleInput; setDraft: (v: FleetVehicleInput) => void; save: () => void; saving: boolean }) { const set = (p: FleetVehicleInput) => setDraft({ ...draft, ...p }); return <div className="space-y-4"><FormSection title="Truck / vehicle"><FormField label="Plate" required><Input value={draft.plateNo ?? ''} onChange={(e) => set({ plateNo: e.target.value.toUpperCase() })} leftIcon={<Truck className="size-4" />} /></FormField><FormField label="Type"><Input value={draft.type ?? ''} onChange={(e) => set({ type: e.target.value })} /></FormField><FormField label="Make / model"><Input value={draft.make ?? ''} onChange={(e) => set({ make: e.target.value })} /></FormField><FormField label="Capacity"><Input value={draft.capacity ?? ''} onChange={(e) => set({ capacity: e.target.value })} /></FormField><FormField label="Status"><Select value={draft.status ?? 'AVAILABLE'} onValueChange={(status) => set({ status })} options={['AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'INACTIVE'].map((value) => ({ value, label: value }))} /></FormField><FormField label="Registration / insurance expiry"><><Textarea value="" readOnly /><p className="text-xs text-muted-foreground">Backend FleetVehicle has no registrationExpiry or insuranceExpiry columns yet.</p></></FormField></FormSection><div className="flex justify-end"><Button onClick={save} loading={saving} kbd="Ctrl+S">Save</Button></div></div> }
function RouteEditor({ draft, setDraft, save, saving, drivers, vehicles }: { draft: DispatchRouteInput; setDraft: (v: DispatchRouteInput) => void; save: () => void; saving: boolean; drivers: Driver[]; vehicles: FleetVehicle[] }) { const set = (p: DispatchRouteInput) => setDraft({ ...draft, ...p }); return <div className="space-y-4"><FormSection title="Dispatch manifest"><FormField label="Route #"><Input value={draft.routeNo ?? 'Auto on save'} readOnly /></FormField><FormField label="Stage"><Select value={draft.stage ?? 'DRAFT'} onValueChange={(stage) => set({ stage })} options={['DRAFT', 'DISPATCHED', 'IN_TRANSIT', 'ARRIVED', 'COMPLETED'].map((value) => ({ value, label: value }))} /></FormField><FormField label="Origin"><Input value={draft.origin ?? ''} onChange={(e) => set({ origin: e.target.value })} /></FormField><FormField label="Destination"><Input value={draft.destination ?? ''} onChange={(e) => set({ destination: e.target.value })} /></FormField><FormField label="Driver"><Select value={draft.driverName ?? undefined} onValueChange={(driverName) => set({ driverName })} options={drivers.map((d) => ({ value: d.name, label: d.name }))} /></FormField><FormField label="Vehicle"><Select value={draft.vehiclePlate ?? undefined} onValueChange={(vehiclePlate) => set({ vehiclePlate })} options={vehicles.map((v) => ({ value: v.plateNo, label: `${v.plateNo}${v.type ? ` · ${v.type}` : ''}` }))} /></FormField><FormField label="Cargo ref"><Input value={draft.cargoRef ?? ''} onChange={(e) => set({ cargoRef: e.target.value })} /></FormField><FormField label="Scheduled"><Input type="datetime-local" value={draft.scheduledAt?.slice(0, 16) ?? ''} onChange={(e) => set({ scheduledAt: e.target.value })} /></FormField><FormField label="Stops JSON"><Textarea value={draft.stops ?? '[]'} onChange={(e) => set({ stops: e.target.value })} /></FormField><FormField label="Remarks"><Textarea value={draft.remarks ?? ''} onChange={(e) => set({ remarks: e.target.value })} /></FormField></FormSection><div className="flex justify-end"><Button onClick={save} loading={saving} kbd="Ctrl+S">Save manifest</Button></div></div> }

