import { useState } from 'react'
import { Bell, Ship } from 'lucide-react'
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Checkbox, Combobox, DataGrid, DateInput, EditableGrid, EmptyState, FormField, FormSection, Input, MoneyInput, PageHeader, Select, SegmentedControl, Skeleton, StatCard, StatusPill, Stepper, Switch, Tabs, Textarea, Timeline, Toolbar, Tooltip } from '../components/ui'
import { formatMoney } from '../lib/format'

interface DemoRow { id: string; module: string; status: string; amount: number }
interface ChargeRow { code: string; qty: string; rate: string }

export default function UIKit() {
  const [tab, setTab] = useState('forms')
  const [density, setDensity] = useState('comfortable')
  const [charges, setCharges] = useState<ChargeRow[]>([{ code: '', qty: '1', rate: '0' }])
  const [demoSwitch, setDemoSwitch] = useState(true)
  const [demoVat, setDemoVat] = useState(true)
  const rows: DemoRow[] = []
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Admin only" title="Kornet UI Kit" description="Living component guide for the v2 logistics + accounting overhaul. Examples show structure only; no fake business records are seeded." primaryAction={<Button kbd="N">Primary action</Button>} />
    <Tabs value={tab} onValueChange={setTab} tabs={[
      { value: 'forms', label: 'Forms', content: <div className="grid gap-5"><FormSection title="Grouped entry" description="Use for dense Logisuite-style data entry."><FormField label="Customer" required><Combobox items={[]} placeholder="Search parties…" createLabel="Create new party…" /></FormField><FormField label="Document number"><Input placeholder="Auto-numbered on save" /></FormField><FormField label="Date"><DateInput /></FormField><FormField label="Amount"><MoneyInput currency="PHP" value={0} /></FormField><FormField label="Mode"><Select options={[{ value: 'ocean', label: 'Ocean' }, { value: 'air', label: 'Air' }]} /></FormField><FormField label="Notes"><Textarea placeholder="Internal note" /></FormField><Checkbox checked={demoVat} onCheckedChange={(v) => setDemoVat(Boolean(v))}>VAT registered</Checkbox><div className="flex items-center gap-3"><Switch checked={demoSwitch} onCheckedChange={setDemoSwitch} aria-label="Demo interactive switch" /><span className="text-sm font-medium">{demoSwitch ? 'Interactive switch is ON' : 'Interactive switch is OFF'}</span></div></FormSection></div> },
      { value: 'data', label: 'Data', content: <div className="grid gap-5"><Toolbar><Input placeholder="Filter current view" className="max-w-sm" /><SegmentedControl label="Density" value={density} onValueChange={setDensity} options={[{ value: 'comfortable', label: 'Comfortable' }, { value: 'compact', label: 'Compact' }]} /></Toolbar><DataGrid data={rows} emptyTitle="No records loaded" density={density as 'comfortable' | 'compact'} columns={[{ id: 'module', header: 'Module', accessor: 'module', sortable: true }, { id: 'status', header: 'Status', cell: (r) => <StatusPill status={r.status} /> }, { id: 'amount', header: 'Amount', cell: (r) => <span className="font-mono tabular-nums">{formatMoney(r.amount)}</span> }]} /><EditableGrid rows={charges} onRowsChange={setCharges} createRow={() => ({ code: '', qty: '1', rate: '0' })} columns={[{ id: 'code', header: 'Code' }, { id: 'qty', header: 'Qty', type: 'number' }, { id: 'rate', header: 'Rate', type: 'money' }]} footer={<span className="font-mono text-sm">Footer totals stay server-authoritative.</span>} /></div> },
      { value: 'feedback', label: 'Feedback', content: <div className="grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>Status palette</CardTitle><CardDescription>Mapped to SPEC document statuses.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><StatusPill status="DRAFT" /><StatusPill status="BOOKED" /><StatusPill status="IN_TRANSIT" /><StatusPill status="CLEARED" /><StatusPill status="HOLD" /><StatusPill status="POSTED" /><Badge status="VOID" /></CardContent></Card><StatCard label="Real API metric slot" value="—" icon={<Ship className="size-5" />} delta="Shows empty until /api/dashboard/summary is available." /><EmptyState title="Empty state" description="Use one helpful action, never fabricated records." action={<Button variant="outline">Create when ready</Button>} /><div className="rounded-xl border bg-card p-5"><Timeline items={[{ id: '1', title: 'Draft saved locally', tone: 'info' }, { id: '2', title: 'Server confirms status', tone: 'success' }]} /></div><div className="rounded-xl border bg-card p-5"><Stepper steps={['Quote','Booking','BL','Invoice','Close','Posted']} current={1} /></div><Tooltip content="Tooltip text"><Button variant="outline"><Bell className="size-4" />Hover/focus</Button></Tooltip><Skeleton className="h-28" /></div> },
    ]} />
  </div>
}
