import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertTriangle, CalendarClock, CreditCard, DollarSign, PackageCheck, Plane, Plus, Search, Ship, Truck } from 'lucide-react'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, EmptyState, PageHeader, Skeleton, StatCard, StatusPill, Toolbar } from '@/components/ui'
import { getDashboardSummary, type DashboardSummary } from '@/api/dashboard'
import { useHotkeys } from '@/hooks/useHotkeys'
import { formatDate, formatMoney, formatNumber } from '@/lib/format'
import { useAuthStore } from '@/stores/authStore'

function countOf(v: unknown) { return typeof v === 'number' ? v : typeof v === 'object' && v && '_all' in v ? Number((v as { _all?: number })._all ?? 0) : 0 }
function fileCount(row: { _count?: number | { _all?: number } }) { return countOf(row._count) }
function CountUp({ value, money }: { value: number; money?: boolean }) { return <motion.span initial={{ opacity: 0 }} animate={{ opacity: 1 }}>{money ? formatMoney(value) : formatNumber(value)}</motion.span> }
function modeIcon(mode: string) { const m = mode.toUpperCase(); if (m.includes('AIR')) return <Plane className="size-4" />; if (m.includes('DOM')) return <Truck className="size-4" />; return <Ship className="size-4" /> }
function toRoute(type: string, id?: string, ref?: string) { if (!id && !ref) return '#'; if (type === 'invoice') return `/billing/invoices?id=${id ?? ref}`; if (type === 'pd') return `/logistics/pd-orders?id=${id ?? ref}`; return `/logistics/ocean-export?id=${id ?? ref}` }
function asRecord(row: unknown) { return (row ?? {}) as Record<string, unknown> }
function rowText(row: Record<string, unknown>, keys: string[]) { for (const k of keys) if (row[k]) return String(row[k]); return '—' }
function rowDate(row: Record<string, unknown>, keys: string[]) { for (const k of keys) if (row[k]) return formatDate(String(row[k])); return '—' }

function WorkList({ title, rows, dateKeys, type }: { title: string; rows?: Array<Record<string, unknown>>; dateKeys: string[]; type: string }) {
  const items = rows ?? []
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Click any row to open the source record.</CardDescription></CardHeader><CardContent>{items.length ? <div className="divide-y rounded-lg border">{items.map((raw, index) => { const row = asRecord(raw); const id = String(row.id ?? ''); const ref = rowText(row, ['fileNo', 'invoiceNo', 'billNo', 'orderNo', 'reference']); return <a key={`${ref}-${index}`} href={toRoute(type, id, ref)} className="flex items-center justify-between gap-3 p-3 text-sm transition hover:bg-muted"><span><span className="font-semibold">{ref}</span><span className="ml-2 text-muted-foreground">{rowText(row, ['podCode', 'status', 'customer', 'billToName'])}</span></span><span className="font-mono text-xs text-muted-foreground">{rowDate(row, dateKeys)}</span></a> })}</div> : <EmptyState title={`No ${title.toLowerCase()}`} description="The server returned no records for this queue." />}</CardContent></Card>
}

export default function DashboardPage() {
  const role = useAuthStore((s) => s.user?.role ?? 'viewer')
  const { data, isLoading, error, refetch } = useQuery({ queryKey: ['dashboard-summary'], queryFn: getDashboardSummary })
  useHotkeys([{ key: '/', description: 'Search', handler: () => window.dispatchEvent(new CustomEvent('kornet:open-command')) }, { key: 'N', description: 'New file', handler: () => { window.location.href = '/logistics/ocean-export?new=1' } }])
  const summary = data ?? {}
  const byMode = useMemo(() => modeCards(summary), [summary])
  const totalActive = byMode.reduce((s, m) => s + m.count, 0)
  const arOutstanding = summary.arOutstanding ?? Object.values(summary.arAging ?? {}).reduce((s, n) => s + Number(n), 0)
  const arOverdue = summary.arOverdue ?? Object.entries(summary.arAging ?? {}).filter(([k]) => k !== 'current').reduce((s, [, n]) => s + Number(n), 0)
  const apDue = summary.apDueThisWeek ?? summary.apDueAmount ?? 0
  const mtd = summary.mtd ?? {}
  const marginPct = mtd.marginPct ?? (mtd.revenue ? ((Number(mtd.profit ?? 0) / Number(mtd.revenue)) * 100) : 0)
  const agingChart = Object.entries(summary.arAging ?? {}).map(([bucket, amount]) => ({ bucket, amount }))
  const statusChart = (summary.filesByStatus ?? []).map((r) => ({ name: `${r.mode ?? ''} ${r.status}`.trim(), count: fileCount(r) }))
  const mtdChart = summary.mtdByMode?.length ? summary.mtdByMode : byMode.map((m) => ({ mode: m.mode, revenue: 0, cost: 0 }))
  const bridgeQueued = (summary.bridgeQueue ?? []).reduce((s, b) => s + fileCount(b), 0)
  const canAccounting = ['accounting', 'accountant', 'manager', 'admin', 'superadmin'].includes(role)
  if (error) return <Card className="m-6"><CardContent className="pt-5"><EmptyState icon={<AlertTriangle />} title="Dashboard unavailable" description="GET /dashboard/summary failed." action={<Button onClick={() => refetch()}>Retry</Button>} /></CardContent></Card>
  return <div className="space-y-5 p-1"><PageHeader eyebrow="Control tower" title="Kornet operations dashboard" description="Live logistics, billing, and accounting queues from server data only." actions={<Button variant="outline" onClick={() => window.dispatchEvent(new CustomEvent('kornet:open-command'))}><Search className="size-4" />Search</Button>} primaryAction={<Button onClick={() => { window.location.href = '/logistics/ocean-export?new=1' }} kbd="N"><Plus className="size-4" />New file</Button>} />
    <Toolbar><Button onClick={() => { window.location.href = '/logistics/ocean-export?new=1' }}><Ship className="size-4" />New Ocean Export file</Button><Button variant="outline" onClick={() => { window.location.href = '/logistics/air-export?new=1' }}><Plane className="size-4" />New Air Export</Button><Button variant="outline" onClick={() => { window.location.href = '/logistics/pd-orders?new=1' }}><Truck className="size-4" />New P/D</Button><Button variant="outline" disabled={!canAccounting} onClick={() => { window.location.href = '/billing/receivables?new=payment' }}><CreditCard className="size-4" />Receive payment</Button></Toolbar>
    {isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-32" />)}</div> : <motion.div initial="hidden" animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: 0.04 } } }} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><motion.div variants={{ hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0 } }}><StatCard label="Active files" value={<CountUp value={totalActive} />} icon={<PackageCheck className="size-5" />} delta={byMode.map((m) => <span key={m.mode} className="mr-2 inline-flex items-center gap-1">{modeIcon(m.mode)}{m.mode}: {m.count}</span>)} /></motion.div><StatCard label="Arrivals next 7 days" value={<CountUp value={(summary.upcomingEtas ?? []).length} />} icon={<CalendarClock className="size-5" />} /><StatCard label="Cutoffs next 72h" value={<CountUp value={(summary.upcomingCutoffs ?? []).length} />} icon={<AlertTriangle className="size-5" />} /><StatCard label="P/D today" value={<CountUp value={Number(summary.pdToday ?? 0)} />} icon={<Truck className="size-5" />} /><StatCard label="Bridge queue" value={<CountUp value={bridgeQueued} />} icon={<CreditCard className="size-5" />} /><StatCard label="AR outstanding / overdue" value={<CountUp value={arOutstanding} money />} delta={formatMoney(arOverdue) + ' overdue'} icon={<DollarSign className="size-5" />} /><StatCard label="AP due this week" value={<CountUp value={apDue} money />} icon={<CreditCard className="size-5" />} /><StatCard label="MTD GP / margin" value={<>{formatMoney(Number(mtd.profit ?? 0))} <span className="text-base text-muted-foreground">{formatNumber(marginPct)}%</span></>} delta={`${formatMoney(Number(mtd.revenue ?? 0))} rev / ${formatMoney(Number(mtd.cost ?? 0))} cost`} icon={<DollarSign className="size-5" />} /></motion.div>}
    <div className="grid gap-4 xl:grid-cols-3"><ChartCard title="Revenue vs cost by mode" data={mtdChart} /><ChartCard title="AR aging" data={agingChart} aging /><ChartCard title="Files by status" data={statusChart} status /></div>
    <div className="grid gap-4 xl:grid-cols-2"><WorkList title="Upcoming ETAs" rows={summary.upcomingEtas as Array<Record<string, unknown>> | undefined} dateKeys={['eta']} type="shipment" /><WorkList title="Cutoffs" rows={summary.upcomingCutoffs as Array<Record<string, unknown>> | undefined} dateKeys={['docCutoff', 'cargoCutoff']} type="shipment" /><WorkList title="Overdue invoices" rows={summary.overdueInvoices as Array<Record<string, unknown>> | undefined} dateKeys={['dueDate']} type="invoice" /><WorkList title="Low-margin files" rows={summary.lowMarginFiles as Array<Record<string, unknown>> | undefined} dateKeys={['updatedAt']} type="shipment" /></div>
    <Card><CardHeader><CardTitle>Top customers MTD</CardTitle><CardDescription>Posted invoice revenue by customer.</CardDescription></CardHeader><CardContent>{summary.topCustomers?.length ? <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{summary.topCustomers.map((c, i) => <div key={`${c.customer ?? c.name}-${i}`} className="rounded-lg border p-3"><p className="truncate text-sm font-semibold">{c.customer ?? c.name ?? 'Unknown'}</p><p className="mt-2 font-mono text-lg">{formatMoney(Number(c.amount ?? c.revenue ?? 0))}</p></div>)}</div> : <EmptyState title="No posted customer revenue this month" />}</CardContent></Card>
  </div>
}
function modeCards(summary: DashboardSummary) { if (summary.activeFilesByMode) return Object.entries(summary.activeFilesByMode).map(([mode, count]) => ({ mode, count: Number(count) })); const modes: Record<string, number> = {}; for (const r of summary.filesByStatus ?? []) { if (!['CLOSED', 'CANCELLED'].includes(String(r.status).toUpperCase())) modes[String(r.mode ?? 'FILES')] = (modes[String(r.mode ?? 'FILES')] ?? 0) + fileCount(r) } return Object.entries(modes).map(([mode, count]) => ({ mode, count })) }
function ChartCard({ title, data, aging, status }: { title: string; data: Array<Record<string, string | number>>; aging?: boolean; status?: boolean }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="h-72">{data.length ? <ResponsiveContainer width="100%" height="100%">{aging || status ? <BarChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.25} /><XAxis dataKey={aging ? 'bucket' : 'name'} hide={status} /><YAxis /><Tooltip /><Bar dataKey={aging ? 'amount' : 'count'} fill="hsl(var(--secondary))" radius={[6, 6, 0, 0]} /></BarChart> : <AreaChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.25} /><XAxis dataKey="mode" /><YAxis /><Tooltip /><Area type="monotone" dataKey="revenue" stroke="hsl(var(--secondary))" fill="hsl(var(--secondary) / .18)" /><Area type="monotone" dataKey="cost" stroke="hsl(var(--destructive))" fill="hsl(var(--destructive) / .12)" /></AreaChart>}</ResponsiveContainer> : <EmptyState title="No chart data" />}</CardContent></Card> }
export function DashboardStatusLegend({ status }: { status: string }) { return <StatusPill status={status} /> }
