import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { ArrowRight, Download, Lock, LogOut, PackageSearch, Search } from 'lucide-react'
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, EmptyState, FormField, Input, PageHeader, Skeleton, Timeline, type StatusTone } from '@/components/ui'
import { portalLogin, portalShipments, publicTrack, type PortalShipment, type TrackingResult } from '@/api/portal'
import { formatDate } from '@/lib/format'

const tokenKey = 'kornet-portal-token'
const userKey = 'kornet-portal-user'
function getToken() { return localStorage.getItem(tokenKey) ?? '' }
function setSession(token: string, user: unknown) { localStorage.setItem(tokenKey, token); localStorage.setItem(userKey, JSON.stringify(user)) }
function clearSession() { localStorage.removeItem(tokenKey); localStorage.removeItem(userKey) }
function getUserName() { try { return JSON.parse(localStorage.getItem(userKey) || '{}').customerName as string | undefined } catch { return undefined } }
function statusTone(status: string): StatusTone { const s = status.toUpperCase(); return s.includes('DELIVER') || s.includes('CLEAR') ? 'success' : s.includes('CANCEL') || s.includes('HOLD') ? 'danger' : s.includes('ARRIV') ? 'warning' : 'info' }

export function PortalLoginPage() {
  const [companyCode, setCompanyCode] = useState('KORNET'); const [username, setUsername] = useState(''); const [password, setPassword] = useState('')
  const login = useMutation({ mutationFn: () => portalLogin({ companyCode, username, password }), onSuccess: (data) => { setSession(data.token, data.user); toast.success('Welcome to Kornet Portal'); window.location.href = '/portal' }, onError: () => toast.error('Invalid portal credentials') })
  return <PublicFrame><Card className="mx-auto w-full max-w-md"><CardHeader><CardTitle className="flex items-center gap-2"><Lock className="size-5" /> Customer portal</CardTitle><CardDescription>Sign in with the web account provided by Kornet Express.</CardDescription></CardHeader><CardContent className="grid gap-4"><FormField label="Company"><Input value={companyCode} onChange={(e) => setCompanyCode(e.target.value.toUpperCase())} /></FormField><FormField label="Username"><Input value={username} onChange={(e) => setUsername(e.target.value)} autoFocus /></FormField><FormField label="Password"><Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && login.mutate()} /></FormField><Button loading={login.isPending} onClick={() => login.mutate()}>Sign in <ArrowRight className="size-4" /></Button><a href="/track" className="text-center text-sm text-secondary">Track without signing in</a></CardContent></Card></PublicFrame>
}

export function PortalHomePage() {
  const [token, setToken] = useState(getToken())
  const { data, isLoading, error } = useQuery({ queryKey: ['portal-shipments', token], queryFn: () => portalShipments(token), enabled: Boolean(token) })
  if (!token) return <PortalLoginPage />
  return <PublicFrame><div className="mx-auto w-full max-w-6xl space-y-5"><PageHeader eyebrow="Kornet Express" title={`Welcome${getUserName() ? `, ${getUserName()}` : ''}`} description="Track your shipments, milestones, documents and invoice visibility from your customer account." actions={<Button variant="outline" onClick={() => { clearSession(); setToken('') }}><LogOut className="size-4" />Sign out</Button>} />{error ? <EmptyState title="Portal session expired" description="Please sign in again." action={<Button onClick={() => { clearSession(); setToken('') }}>Sign in</Button>} /> : isLoading ? <Skeleton className="h-72" /> : <ShipmentGrid rows={data ?? []} />}<div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Documents</CardTitle><CardDescription>Download links appear when the backend exposes portal document endpoints.</CardDescription></CardHeader><CardContent><EmptyState icon={<Download />} title="No downloadable documents endpoint yet" description="Current portal API exposes shipment list and public tracking only." /></CardContent></Card><Card><CardHeader><CardTitle>Invoices balance</CardTitle><CardDescription>Invoice visibility requires a portal invoices endpoint and account permission mapping.</CardDescription></CardHeader><CardContent><EmptyState title="Invoice balance not available" description="Backend gap: /api/portal/invoices is not implemented." /></CardContent></Card></div></div></PublicFrame>
}
function ShipmentGrid({ rows }: { rows: PortalShipment[] }) { if (!rows.length) return <EmptyState title="No shipments visible" description="Your web account is active, but no shipments are linked to your party yet." />; return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map((s) => <a key={s.id} href={`/track/${encodeURIComponent(s.fileNo)}`} className="rounded-2xl border bg-card p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm text-muted-foreground">{s.fileNo}</p><h3 className="mt-1 text-lg font-semibold">{s.mode} {s.direction}</h3></div><Badge status={s.status} tone={statusTone(s.status)} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><span><span className="block text-muted-foreground">ETD</span>{formatDate(s.etd)}</span><span><span className="block text-muted-foreground">ETA</span>{formatDate(s.eta)}</span></div></a>)}</div> }

export function PublicTrackingPage() {
  const pathRef = decodeURIComponent(window.location.pathname.replace(/^\/track\/?/, ''))
  const [ref, setRef] = useState(pathRef); const [submitted, setSubmitted] = useState(pathRef)
  const { data, isLoading, error } = useQuery({ queryKey: ['public-track', submitted], queryFn: () => publicTrack(submitted), enabled: Boolean(submitted) })
  return <PublicFrame><div className="mx-auto w-full max-w-5xl space-y-5"><Card><CardContent className="pt-5"><div className="flex flex-col gap-3 sm:flex-row"><Input leftIcon={<Search className="size-4" />} value={ref} onChange={(e) => setRef(e.target.value)} placeholder="Enter file, BL, or AWB reference" onKeyDown={(e) => e.key === 'Enter' && setSubmitted(ref)} /><Button onClick={() => setSubmitted(ref)}>Track</Button></div></CardContent></Card>{!submitted ? <EmptyState icon={<PackageSearch />} title="Enter a tracking reference" description="Public tracking shows minimal status, route and public milestones only." /> : isLoading ? <Skeleton className="h-80" /> : error ? <EmptyState title="Reference not found" description="Check your file, BL, or AWB number and try again." /> : data ? <TrackingResultView data={data} /> : null}</div></PublicFrame>
}
function TrackingResultView({ data }: { data: TrackingResult }) { const items = useMemo(() => data.milestones.map((m, i) => ({ id: `${m.code}-${i}`, title: m.subStatus || m.code, time: formatDate(m.eventAt), tone: statusTone(m.subStatus || m.code), description: [m.location, m.notes].filter(Boolean).join(' — ') })), [data]); return <div className="grid gap-4 lg:grid-cols-[22rem_1fr]"><Card><CardHeader><CardTitle>{data.shipment.fileNo}</CardTitle><CardDescription>{data.shipment.mode}</CardDescription></CardHeader><CardContent className="space-y-3"><Badge status={data.shipment.status} tone={statusTone(data.shipment.status)} /><p><span className="text-muted-foreground">Origin</span><br />{data.shipment.origin ?? '—'}</p><p><span className="text-muted-foreground">Destination</span><br />{data.shipment.destination ?? '—'}</p><p><span className="text-muted-foreground">ETD / ETA</span><br />{formatDate(data.shipment.etd)} → {formatDate(data.shipment.eta)}</p></CardContent></Card><Card><CardHeader><CardTitle>Public milestones</CardTitle></CardHeader><CardContent>{items.length ? <Timeline items={items} /> : <EmptyState title="No public milestones yet" />}</CardContent></Card></div> }
function PublicFrame({ children }: { children: React.ReactNode }) { return <main className="min-h-dvh bg-[radial-gradient(circle_at_top_left,hsl(var(--secondary)/.18),transparent_34rem),linear-gradient(180deg,hsl(var(--background)),hsl(var(--muted)/.35))] p-4 text-foreground sm:p-8"><div className="mx-auto mb-8 flex max-w-6xl items-center justify-between"><a href="/portal" className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-lg">KE</span><span><span className="block text-lg font-semibold">Kornet Express</span><span className="text-xs text-muted-foreground">Logistics visibility portal</span></span></a><a href="/track" className="text-sm font-semibold text-secondary">Public tracking</a></div>{children}</main> }
